-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/FTixMqmBsBULDTY
mcd6ptIjMFc5RixDiBKsWTBtjgugCgYIKoZIzj0DAQehRANCAAQkFiUTO+4E7jQL
RF0nYh5wnKJZuaqA5KQphHI0jZgCRsp16JXc3NOs+a5v09lbYaZaVhwQSAsaO4AP
5b3ska7z
-----END PRIVATE KEY-----