# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Install pod dependencies"
      lane :install_pods do
      cocoapods(clean: true,use_bundle_exec: false)
  end
  
  desc "Update Build number and archive the project."
  lane :EkaQA do
      install_pods
      increment_version_number_in_plist(version_number: 'QaVersionNo' ,target: 'EkaAnalyticsQA')
      increment_build_number_in_plist(build_number: 'QaBuildNo',target: 'EkaAnalyticsQA')
      build_app(scheme: "EkaAnalyticsQA")
  end 
  
  desc "Update Build number and archive the project."
  lane :Eka do
      install_pods
      increment_version_number_in_plist(version_number: 'VersionNo' ,target: 'EkaAnalytics')
      increment_build_number_in_plist(build_number: 'BuildNo',target: 'EkaAnalytics')
      build_app(scheme: "EkaAnalytics")
  end 
 
end
